### ISSUE TITLE
ea get token not working

### ISSUE THREAD

**Issue by medhatzak86** [anadius/ea-get-token#2]
i tried more than browser with the latest version of origin helper and ea get token  and still have error 
so can you please check what browser is working with script beacuase it is not generating any tokens anymore
note ( tried firefox + edge + brave + Epic Privacy Browser )

**Comment by anadius** [comment]
Then maybe read the damn error message?

**Comment by medhatzak86** [comment]
Error: Unknown type - text/xml

**Comment by anadius** [comment]
Don't use a proxy/VPN in your browser. Use the UserScript instead of the HTML file - lower chance of you messing it up. The newest UserScript is version 2.1.12. I tested it right this moment and everything works fine. Also, if `get_token` shows your username and IDs (lines 2-4) then the token it grabbed (line 1) works as intended. And since you don't have a problem with this program - don't ask here.

**Comment by medhatzak86** [comment]
can you plase tell me what browser ?
